name: temp_package_name
description: temp_package_description

version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3
  get_it: ^7.6.4
  easy_localization: ^3.0.3
  go_router: ^12.1.3

  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  jwt_decode: ^0.3.1
  connectivity_plus: ^5.0.2
  hive: ^3.0.0-dev
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  flutter_keyboard_visibility: ^5.4.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  file: ^7.0.0
  url_strategy: ^0.2.0
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.3.8
  dotted_border: ^2.1.0
  intl: ^0.18.1
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  universal_html: ^2.2.4
  sentry_flutter: ^7.14.0
    
  _iwu_pack: ^0.0.5

dependency_overrides:
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
