name: boilerplate
description: boilerplate

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.4.0

  #SignIn social
  # firebase_core: ^2.7.0
  # google_sign_in: ^6.0.1
  # flutter_facebook_auth: ^5.0.7
  # sign_in_with_apple: ^4.3.0

  dio: ^5.1.1
  logger: ^1.3.0
  connectivity_plus: ^3.0.3
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  rxdart: ^0.27.7
  path_provider: ^2.0.14
  responsive_builder: ^0.6.4
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  modal_bottom_sheet: ^2.1.2
  overlay_support: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 

  # fonts: 
  #   - family: Gilroy
  #     fonts:
  #       - asset: assets/fonts/SVN_Gilroy_Thin.otf
  #         weight: 100
  #       - asset: assets/fonts/SVN_Gilroy_Xlight.otf
  #         weight: 200
  #       - asset: assets/fonts/SVN_Gilroy_Light.otf
  #         weight: 300
  #       - asset: assets/fonts/SVN_Gilroy_Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/SVN_Gilroy_Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/SVN_Gilroy_SemiBold.otf
  #         weight: 600
  #       - asset: assets/fonts/SVN_Gilroy_Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/SVN_Gilroy_XBold.otf
  #         weight: 800
  #       - asset: assets/fonts/SVN_Gilroy_Black.otf
  #         weight: 900 